title: Surbhi Goel's Website
show_downloads: true
theme: jekyll-theme-minimal
exclude:
  - assets/files/CV.pdf
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  notes:
    output: true
    permalink: /notes/:title/

markdown: CommonMarkGfm
